### ISSUE TITLE
Backend setup

### ISSUE THREAD

**Issue by sinsinkun** [Dragontalker/peak-everest-furniture#1]

**Comment by Dragontalker** [comment]
Current back end deployed and MongoDB Atlas connection tested, see issue #19 for more details.

**Comment by Dragontalker** [comment]
Product data seeded to MongoDB Atlas and tested, see issue #20 for more details.

**Comment by Dragontalker** [comment]
User data seeded to MongoDB Atlas and tested, see issue #21 for more details.
